# Number of epochs
N_EPOCHS: 15

#Batch size
BATCH_SIZE: 32

# Learning rate
LEARNING_RATE: 0.001

N_CONV_EPOCHS: 100

RANDOM_SEED: 0

ALVA:
  N_GENERATED_SAMPLES: 25
  N_TIMEOUT: 2000
  EPSILON: 0.3
  TARGET_CLASS: 8

GENERATOR:
  LATENT_DIM: 100
  OUTPUT_DIM: [1,28,28]
